# Generated by Django 5.0.6 on 2024-06-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
