# Generated by Django 5.0.6 on 2024-06-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
