# Generated by Django 5.0.6 on 2024-06-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chetan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_out', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
