# Generated by Django 5.0.6 on 2024-06-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_chetan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chetan',
        ),
    ]
