# Generated by Django 5.0.6 on 2024-06-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
